USE UserOrders;

IF OBJECT_ID('dbo.Orders','U') IS NOT NULL
DROP TABLE dbo.Orders;

IF OBJECT_ID('dbo.Users','U') IS NOT NULL
DROP TABLE dbo.Users;

CREATE TABLE Users
(Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Id PRIMARY KEY,
Name VARCHAR(256) NOT NULL,
Bdate Date NOT NULL,
Score INT NULL
);

GO



CREATE TABLE Orders
(UserId INT NOT NULL CONSTRAINT FK_User
FOREIGN KEY (UserId)
	REFERENCES Users(Id)
	ON DELETE CASCADE
	ON UPDATE NO ACTION,
[Desc] VARCHAR(256) NOT NULL,
Odate Date NOT NULL,
Cnt INT NULL,
CONSTRAINT PK_UserDate PRIMARY KEY(UserId,Odate)
);

GO